import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User.js';

dotenv.config();

const checkAdmin = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB Connected');

        const adminUser = await User.findOne({ email: 'admin@example.com' });

        if (adminUser) {
            console.log('Admin user found in User collection:');
            console.log(`Email: ${adminUser.email}`);
            console.log(`Role: ${adminUser.role}`);
            // Force update role to admin just in case
            if (adminUser.role !== 'admin') {
                adminUser.role = 'admin';
                await adminUser.save();
                console.log('User role updated to admin');
            }
        } else {
            console.log('Admin user NOT found in User collection. Creating one...');
            const newUser = await User.create({
                name: 'Admin User',
                email: 'admin@example.com',
                password: '123456', // The hash will be generated by the pre-save hook in User model
                role: 'admin'
            });
            console.log('Admin user created successfully');
            console.log(`Email: ${newUser.email}`);
            console.log('Password: 123456');
        }

        process.exit();
    } catch (error) {
        console.error('Error:', error);
        process.exit(1);
    }
};

checkAdmin();
